# Reload -> prefix + r

bind r source-file "~/.config/tmux/tmux.conf" \; display "reloaded"

set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-ghostty:RGB:usstyle:extkeys:hyperlinks:sync:clipboard"

set -s escape-time 10
set -g mouse on
set -g history-limit 50000
set -g display-time 4000
set -g allow-passthrough all
set -g focus-events on
set -s extended-keys on
set -g extended-keys-format csi-u
setw -g aggressive-resize on
set -g status-interval 5

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

set -g set-titles on
set -g set-titles-string "#S: #{b:pane_current_path}"

set -g mouse on
set -g set-clipboard on
bind -T copy-mode MouseDragEnd1Pane send -X copy-selection-no-clear
bind -T copy-mode DoubleClick1Pane send -X select-word \; send -X copy-selection-no-clear


bind -N "sesh" o display-popup -h 60% -w 60% -E "sesh picker -i"
set -g detach-on-destroy off 


set-environment -g TMUX_FZF_LAUNCH_KEY "f"
set-environment -g TMUX_FZF_OPTIONS "-p -w 60% -h 60% -m"

set-environment -g TMUX_PLUGIN_MANAGER_PATH "$HOME/.local/share/tmux/plugins"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g @plugin 'erikw/tmux-powerline'

set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# Install -> prefix + I, update -> prefix + U, clean -> prefix + M-u
run "$HOME/.local/share/tmux/plugins/tpm/tpm"
